/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/


package com.company;

public class Main {

    public static void main(String[] args) {

        int num1 = 1;
        int num2 = 2;
        int newNum = 0;
        int numTotal = 0;

        do {
            newNum = num1 + num2;
            num1 = num2;
            num2 = newNum;

            if(newNum % 2 == 0){
                numTotal += newNum;
            }

        } while (num2 < 4000000);

        System.out.println(numTotal);


    }
}

